
spring:
  application:
    name: us-consumer
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:7777/eureka/
feign:
  hystrix:
    enabled: true
us-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule