spring:
  application:
    name: eureka-server
  security:
    user:
      password: root
      name: root
server:
  port: 7777
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7777/eureka/

